#!/bin/bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	items=$(find ~/Work -maxdepth 1 -mindepth 1 -type d)
	items+=("\n$HOME")
	items+=("\n$HOME/dotfiles")

	selected=$(echo -en "${items[@]}" | awk '{ print length(), $0 | "sort -n" }' | awk -F" " '{ print $2}' | fzf)
fi

[[ -z "$selected" ]] && exit 1

[[ "$selected" == "$HOME" ]] && sessname="general" || sessname=$(basename "$selected" | tr . _)

tmux switch-client -t "$sessname" >/dev/null
if [[ $? -eq 0 ]]; then
	exit 0
fi

tmux new-session -c "$selected" -d -s "$sessname" -n "work" && tmux switch-client -t "$sessname" || tmux new -c "$selected" -A -s "$sessname" >/dev/null
